import { NextResponse } from 'next/server';
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import path from 'path';

const execAsync = promisify(exec);

const VAULT_PATH = process.env.VAULT_PATH || path.join(process.cwd(), '..', 'AI_Employee_Vault');
const PROJECT_PATH = process.env.PROJECT_ROOT || path.join(process.cwd(), '..');

interface GenerateRequest {
  lookbackDays?: number;
  template?: 'daily' | 'weekly' | 'monthly';
}

function getVaultStats() {
  const folders = ['Needs_Action', 'Pending_Approval', 'Done', 'In_Progress', 'Approved', 'Rejected', 'Failed'];
  const stats: Record<string, number> = {};

  folders.forEach(folder => {
    const folderPath = path.join(VAULT_PATH, folder);
    if (fs.existsSync(folderPath)) {
      stats[folder] = fs.readdirSync(folderPath).filter(f => f.endsWith('.md')).length;
    } else {
      stats[folder] = 0;
    }
  });

  return stats;
}

function getRecentActivity(days: number = 7): string[] {
  const activity: string[] = [];
  const folders = ['Done', 'Approved', 'Rejected'];
  const threshold = new Date();
  threshold.setDate(threshold.getDate() - days);

  for (const folder of folders) {
    const folderPath = path.join(VAULT_PATH, folder);
    if (!fs.existsSync(folderPath)) continue;

    const files = fs.readdirSync(folderPath)
      .filter(f => f.endsWith('.md'))
      .map(filename => {
        const filePath = path.join(folderPath, filename);
        const stats = fs.statSync(filePath);
        return { filename, mtime: stats.mtime };
      })
      .filter(f => f.mtime >= threshold)
      .sort((a, b) => b.mtime.getTime() - a.mtime.getTime())
      .slice(0, 10);

    for (const file of files) {
      const subject = file.filename
        .replace(/^(EMAIL_|WHATSAPP_|TRANSACTION_|RESPONSE_|APPROVAL_|PLAN_)/, '')
        .replace(/^\d{8}_\d{6}_/, '')
        .replace(/_/g, ' ')
        .replace('.md', '');
      activity.push(`[${folder}] ${subject}`);
    }
  }

  return activity.slice(0, 15);
}

function generateBriefingContent(template: string, lookbackDays: number): string {
  const stats = getVaultStats();
  const activity = getRecentActivity(lookbackDays);
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0];
  const dayName = now.toLocaleDateString('en-US', { weekday: 'long' });

  const templateNames: Record<string, string> = {
    daily: 'Daily Snapshot',
    weekly: 'Weekly CEO Briefing',
    monthly: 'Monthly Review',
  };

  const periodDescriptions: Record<string, string> = {
    daily: 'past 24 hours',
    weekly: 'past 7 days',
    monthly: 'past 30 days',
  };

  const title = templateNames[template] || 'CEO Briefing';
  const period = periodDescriptions[template] || `past ${lookbackDays} days`;

  const content = `---
type: briefing
template: ${template}
generated_at: ${now.toISOString()}
lookback_days: ${lookbackDays}
status: generated
---

# ${title} - ${dateStr} (${dayName})

## Executive Summary

This ${template} briefing provides an overview of AI Employee performance and business metrics for the ${period}.

## Vault Status

| Folder | Count |
|--------|-------|
| Needs Action | ${stats.Needs_Action || 0} |
| Pending Approval | ${stats.Pending_Approval || 0} |
| In Progress | ${stats.In_Progress || 0} |
| Completed (Done) | ${stats.Done || 0} |
| Approved | ${stats.Approved || 0} |
| Rejected | ${stats.Rejected || 0} |
| Failed | ${stats.Failed || 0} |

## Performance Metrics

- **Total Items Processed**: ${(stats.Done || 0) + (stats.Approved || 0) + (stats.Rejected || 0)}
- **Success Rate**: ${stats.Done || 0 > 0 ? Math.round(((stats.Done + stats.Approved) / (stats.Done + stats.Approved + stats.Failed + stats.Rejected)) * 100) : 0}%
- **Items Requiring Attention**: ${stats.Needs_Action || 0}
- **Pending Human Review**: ${stats.Pending_Approval || 0}

## Recent Activity

${activity.length > 0 ? activity.map(a => `- ${a}`).join('\n') : '- No recent activity recorded'}

## Recommendations

${stats.Needs_Action > 5 ? '- **High Priority**: Review items in Needs_Action folder\n' : ''}${stats.Pending_Approval > 3 ? '- Review pending approval items to prevent backlog\n' : ''}${stats.Failed > 0 ? '- Investigate failed items to prevent recurring issues\n' : ''}- Continue monitoring system performance
- Ensure watchers are running smoothly

---
*Generated by AI Employee Dashboard on ${now.toISOString()}*
`;

  return content;
}

export async function POST(request: Request) {
  try {
    const body: GenerateRequest = await request.json();
    const { lookbackDays = 7, template = 'weekly' } = body;

    // First, try to run the Python briefing generator
    const pythonScript = path.join(PROJECT_PATH, 'ceo_briefing_generator.py');
    let usedPython = false;

    if (fs.existsSync(pythonScript)) {
      try {
        // Try to run the Python script
        const { stderr } = await execAsync(
          `python "${pythonScript}" --lookback ${lookbackDays}`,
          { cwd: PROJECT_PATH, timeout: 60000 }
        );

        if (!stderr || !stderr.includes('Error')) {
          // Python script succeeded, find the generated file
          const briefingsPath = path.join(VAULT_PATH, 'Briefings');
          if (fs.existsSync(briefingsPath)) {
            const files = fs.readdirSync(briefingsPath)
              .filter(f => f.endsWith('.md'))
              .sort()
              .reverse();

            if (files.length > 0) {
              const latestFile = files[0];
              const content = fs.readFileSync(path.join(briefingsPath, latestFile), 'utf-8');

              return NextResponse.json({
                success: true,
                filename: latestFile,
                content,
                source: 'python',
              });
            }
          }
          usedPython = true;
        }
      } catch {
        console.log('Python generator not available, using built-in generator');
      }
    }

    // Fallback: Generate briefing using built-in JavaScript
    const content = generateBriefingContent(template, lookbackDays);
    const now = new Date();
    const dateStr = now.toISOString().split('T')[0];
    const dayName = now.toLocaleDateString('en-US', { weekday: 'long' });
    const filename = `${dateStr}_${dayName}_Briefing.md`;

    // Save to Briefings folder
    const briefingsPath = path.join(VAULT_PATH, 'Briefings');
    if (!fs.existsSync(briefingsPath)) {
      fs.mkdirSync(briefingsPath, { recursive: true });
    }

    const filePath = path.join(briefingsPath, filename);
    fs.writeFileSync(filePath, content);

    return NextResponse.json({
      success: true,
      filename,
      content,
      source: usedPython ? 'python' : 'builtin',
    });

  } catch (error) {
    console.error('Briefing generation error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to generate briefing',
      },
      { status: 500 }
    );
  }
}
