import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

const VAULT_PATH = process.env.VAULT_PATH ||
  path.join(process.cwd(), '..', 'AI_Employee_Vault');

/* ── Parse the email markdown file ── */
function extractEmailData(content: string) {
  // Handle both table format (| **From** | `value` |) and plain (**From**: value)
  const fromMatch    = content.match(/\*\*From\*\*.*?`([^`]+)`/) ||
                       content.match(/\*\*From\*\*[:\s]+([^\n|`]+)/);
  const subjectMatch = content.match(/\*\*Subject\*\*.*?`([^`]+)`/) ||
                       content.match(/\*\*Subject\*\*[:\s]+([^\n|`]+)/);
  const emailIdMatch = content.match(/email_id:\s*(.+)/);

  // Body lives inside a fenced block or after ## Email Body / ## 📝 Email Body
  const bodyFenced = content.match(/## (?:📝 )?Email Body[\s\S]*?```[^\n]*\n([\s\S]+?)```/);
  const bodyPlain  = content.match(/## (?:📝 )?Email Body\s*\n+([\s\S]+?)(?:\n##|$)/);
  // Also handle blockquote format (> lines)
  const bodyQuote  = content.match(/> \*\*Original Message:\*\*\s*\n([\s\S]+?)(?:\n---|\n##|$)/);

  const sender  = fromMatch    ? fromMatch[1].trim()    : '';
  const subject = subjectMatch ? subjectMatch[1].trim() : 'No Subject';
  const body    = bodyFenced   ? bodyFenced[1].trim()
                : bodyPlain    ? bodyPlain[1].trim()
                : bodyQuote    ? bodyQuote[1].replace(/^>\s?/gm, '').trim() : '';
  const emailId = emailIdMatch ? emailIdMatch[1].trim() : '';

  return { sender, subject, body, emailId };
}

/* ── Call Groq to generate a reply ── */
async function generateReply(
  sender: string, subject: string, body: string
): Promise<string> {
  // Read GROQ key from project .env
  const envPath = path.join(process.cwd(), '..', '.env');
  let groqKey = process.env.GROQ_API_KEY || '';

  if (!groqKey && fs.existsSync(envPath)) {
    for (const line of fs.readFileSync(envPath, 'utf-8').split('\n')) {
      const m = line.match(/^groq_api_key\s*=\s*(.+)/i);
      if (m) { groqKey = m[1].trim(); break; }
    }
  }

  if (!groqKey) throw new Error('GROQ_API_KEY not found in .env');

  const prompt =
    `You are a professional AI business email assistant. ` +
    `Draft a polished, concise reply to the email below.\n\n` +
    `From: ${sender}\nSubject: ${subject}\n\nBody:\n${body.slice(0, 2000)}\n\n` +
    `Guidelines:\n- Professional but friendly tone\n- Address all points raised\n` +
    `- Proper grammar and punctuation\n\n` +
    `Write ONLY the email body text. Start with an appropriate greeting ` +
    `(e.g. 'Dear ...' or 'Hi ...'). End with a professional sign-off (e.g. 'Best regards,\\nAI Employee').`;

  const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${groqKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'llama-3.1-8b-instant',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 600,
      temperature: 0.7,
    }),
  });

  if (!res.ok) throw new Error(`Groq API error: ${res.status} ${await res.text()}`);
  const data = await res.json();
  return data.choices[0].message.content.trim();
}

/* ── POST handler ── */
export async function POST(req: NextRequest) {
  try {
    const { filename, folder } = await req.json() as { filename: string; folder: string };

    if (!filename || !folder) {
      return NextResponse.json({ error: 'Missing filename or folder' }, { status: 400 });
    }

    const filePath = path.join(VAULT_PATH, folder, filename);
    if (!fs.existsSync(filePath)) {
      return NextResponse.json({ error: 'Email file not found' }, { status: 404 });
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    const { sender, subject, body, emailId } = extractEmailData(content);

    if (!sender) {
      return NextResponse.json({ error: 'Could not parse sender from email file' }, { status: 400 });
    }

    // Generate AI reply
    const replyBody = await generateReply(sender, subject, body);

    // Build Pending_Approval filename
    const ts = new Date().toISOString().slice(0, 19).replace('T', '_').replace(/:/g, '');
    const cleanSubject = subject
      .slice(0, 40)
      .replace(/[^a-zA-Z0-9 \-_]/g, '')
      .trim()
      .replace(/\s+/g, '_');
    const draftFilename = `RESPONSE_${ts}_${cleanSubject}.md`;

    // Write draft file
    const pendingDir = path.join(VAULT_PATH, 'Pending_Approval');
    fs.mkdirSync(pendingDir, { recursive: true });

    const draftContent = `---
email_id: ${emailId}
reply_to: ${sender}
original_subject: ${subject}
created_at: ${new Date().toISOString()}
status: pending_approval
---

# Email Response Draft

## To
${sender}

## Subject
Re: ${subject}

## Body
${replyBody}

## Notes
Auto-generated by AI Employee (Groq llama-3.1-8b-instant). Review before sending.

---
To approve: Move this file to /Approved
To reject: Delete this file or move to /Done
`;

    fs.writeFileSync(path.join(pendingDir, draftFilename), draftContent, 'utf-8');

    return NextResponse.json({ success: true, draftFilename, preview: replyBody.slice(0, 200) });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
